/**
 * Base entity interface for all FullTank domain entities.
 * @remarks IDs match the numeric Long values generated by the backend.\n * @author FullTank Platform
 */
export interface BaseEntity {
  id: number;
}
